[fan.cpu]
sensor_name = "k10temp"
sensor_input = "temp1_input"
pwm_name = "nct6686"
pwm_input = "pwm1"
[[fan.cpu.steps]]
temp = 30
power = 30
[[fan.cpu.steps]]
temp = 50
power = 50
[[fan.cpu.steps]]
temp = 70
power = 70
[[fan.cpu.steps]]
temp = 75
power = 85

[fan.case]
sensor_name = "k10temp"
sensor_input = "temp1_input"
pwm_name = "nct6686"
pwm_input = "pwm2"
[[fan.case.steps]]
temp = 30
power = 30
[[fan.case.steps]]
temp = 50
power = 40
[[fan.case.steps]]
temp = 70
power = 50
[[fan.case.steps]]
temp = 75
power = 70

[fan.gpu]
sensor_name = "amdgpu"
sensor_input = "temp1_input"
pwm_name = "nct6686"
pwm_input = "pwm4"
[[fan.gpu.steps]]
temp = 30
power = 30
[[fan.gpu.steps]]
temp = 50
power = 50
[[fan.gpu.steps]]
temp = 60
power = 70
[[fan.gpu.steps]]
temp = 70
power = 80
